"""Tests for analysis.sponsors.

Success criteria:
  classify: the hand list wins over the markers, an industry marker wins over
    a personal title, and anything the two cannot settle is Unclassified
    rather than pushed into whichever answer the chart wanted
  individuals: a person sponsoring their own trial keeps the trial, counts as
    academic, and loses the name -- PROJECT_SPEC 3.2b
  markers: whole-word only, so 'AB' does not match inside ABBOTT and the
    rule keeps meaning something
  share_by_year: three classes summing to 100%, because a trial has exactly
    one sponsor
  phase_four_by_year: phase IV counted within each class, which is what
    separates "the group does less of it" from "the group got smaller"
  families: candidates are generated by blocking and decided by reading, so
    the two Mercks stay apart and Roche's two blocks come together; family
    membership is also evidence of being a company
  against the database: the classification settles 95.0% of trials, and the
    two findings 3.3 quotes
"""

import re
import sqlite3
import unittest
from pathlib import Path

from analysis.sponsors import (
    ACADEMIC,
    CLASSES,
    FAMILIES,
    HAND_CLASSIFIED,
    INDIVIDUAL,
    INDUSTRY,
    UNCLASSIFIED,
    classified_studies,
    classify,
    display_name,
    families_figure,
    family_of,
    family_review,
    is_individual,
    phase_four_by_year,
    phase_four_figure,
    review_page,
    share_by_year,
    share_figure,
    top_families,
)

DB_PATH = Path(__file__).resolve().parents[1] / "data" / "trials.db"

requires_database = unittest.skipUnless(
    DB_PATH.exists(),
    "data/trials.db is a build artifact; run `python run_pipeline.py build`")


class TestClassify(unittest.TestCase):
    def test_a_legal_form_makes_it_industry(self):
        for name in ("Novartis Farmacéutica, S.A.", "Pfizer Inc.",
                     "AbbVie Deutschland GmbH & Co. KG", "AstraZeneca AB",
                     "Novo Nordisk A/S", "BioNTech SE"):
            with self.subTest(sponsor=name):
                self.assertEqual(classify(name), INDUSTRY)

    def test_an_institution_makes_it_academic(self):
        for name in ("Hospital Universitario La Paz",
                     "Fundació Clínic per a la Recerca Biomèdica",
                     "Universidad de Navarra", "CIBER de Enfermedades"):
            with self.subTest(sponsor=name):
                self.assertEqual(classify(name), ACADEMIC)

    def test_the_hand_list_beats_the_markers(self):
        # Servier's research arm carries 'Institut' and is still Servier.
        self.assertEqual(classify("Institut de Recherches Internationales "
                                  "Servier"), INDUSTRY)
        # And a name with no marker at all that the list settles.
        self.assertEqual(classify("Unicancer"), ACADEMIC)

    def test_a_name_matching_both_is_unclassified_when_unlisted(self):
        # No tie-break rule: one would decide exactly the sponsors nobody
        # checked, in whichever direction the rule was written.
        self.assertEqual(classify("Something Institute Ltd"), UNCLASSIFIED)

    def test_a_name_matching_neither_is_unclassified(self):
        self.assertEqual(classify("Argenx BVBA Unlisted Variant"),
                         UNCLASSIFIED)

    def test_markers_match_whole_words_only(self):
        # 'AB' inside ABBOTT, 'SE' inside SERVIER: a substring rule would
        # classify half the corpus by accident.
        self.assertEqual(classify("ABBOTT"), UNCLASSIFIED)
        self.assertEqual(classify("Fundacion SERVIER"), ACADEMIC)

    def test_every_hand_entry_is_a_real_class(self):
        self.assertTrue(set(HAND_CLASSIFIED.values()) <= {INDUSTRY, ACADEMIC})


class TestIndividuals(unittest.TestCase):
    def test_a_person_is_academic_and_loses_their_name(self):
        name = "Dra. Cristina Avendaño Solá"
        self.assertTrue(is_individual(name))
        self.assertEqual(classify(name), ACADEMIC)
        self.assertEqual(display_name(name), INDIVIDUAL)

    def test_a_company_named_after_a_doctor_is_not_a_person(self):
        # 'Dr. Falk Pharma GmbH' is a German company with 14 trials. The
        # title says how the name begins; the legal form says what it is.
        name = "Dr. Falk Pharma GmbH"
        self.assertFalse(is_individual(name))
        self.assertEqual(classify(name), INDUSTRY)
        self.assertEqual(display_name(name), name)

    def test_an_organisation_keeps_its_name(self):
        self.assertEqual(display_name("Hospital Clínic de Barcelona"),
                         "Hospital Clínic de Barcelona")


class TestShareByYear(unittest.TestCase):
    ROWS = [("s1", 2015, INDUSTRY), ("s2", 2015, INDUSTRY),
            ("s3", 2015, ACADEMIC), ("s4", 2015, UNCLASSIFIED),
            ("s5", 2016, ACADEMIC)]

    def test_the_three_classes_sum_to_100(self):
        # A trial has exactly one sponsor in REEC, which makes this the
        # second chart in the project able to say so.
        for _, shares in share_by_year(self.ROWS):
            with self.subTest(shares=shares):
                self.assertAlmostEqual(sum(shares.values()), 100.0)

    def test_shares_are_of_that_years_trials(self):
        shares = dict(share_by_year(self.ROWS))
        self.assertEqual(shares[2015][INDUSTRY], 50.0)
        self.assertEqual(shares[2016][ACADEMIC], 100.0)

    def test_a_class_with_no_trials_that_year_is_zero(self):
        # Zero here, unlike the phase I subgroup rates, because the class
        # existed and could have sponsored something: the denominator is the
        # year's trials, and it is not empty.
        shares = dict(share_by_year(self.ROWS))
        self.assertEqual(shares[2016][INDUSTRY], 0.0)

    def test_every_class_appears_every_year(self):
        for _, shares in share_by_year(self.ROWS):
            self.assertEqual(set(shares), set(CLASSES))


class TestFigures(unittest.TestCase):
    SHARES = [(2013, {INDUSTRY: 76.0, ACADEMIC: 15.2, UNCLASSIFIED: 8.8}),
              (2026, {INDUSTRY: 85.8, ACADEMIC: 11.6, UNCLASSIFIED: 2.7})]
    PHASE_FOUR = [(2013, INDUSTRY, 577, 37), (2013, ACADEMIC, 115, 35),
                  (2026, INDUSTRY, 578, 12), (2026, ACADEMIC, 78, 32)]

    def test_the_share_chart_carries_the_classified_only_line(self):
        # The confound: unclassified shrank over the window, so some of the
        # industry rise is trials becoming classifiable.
        figure = share_figure(self.SHARES)
        self.assertEqual([trace.name for trace in figure.data][-1],
                         "Industry, of classified trials only")
        self.assertAlmostEqual(list(figure.data[-1].y)[0], 83.3, places=0)
        self.assertAlmostEqual(list(figure.data[-1].y)[-1], 88.1, places=1)

    def test_the_phase_four_chart_is_within_class_shares(self):
        figure = phase_four_figure(self.PHASE_FOUR)
        industry, academic = figure.data
        self.assertAlmostEqual(list(academic.y)[0], 100 * 35 / 115, places=1)
        self.assertAlmostEqual(list(industry.y)[-1], 100 * 12 / 578, places=1)

    def test_both_charts_end_every_line_in_its_value(self):
        for figure in (share_figure(self.SHARES),
                       phase_four_figure(self.PHASE_FOUR)):
            with self.subTest(figure=figure.layout.title.text[:20]):
                self.assertEqual(len(figure.layout.annotations),
                                 len(figure.data))


@requires_database
class TestAgainstDatabase(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.con = sqlite3.connect(
            "file:{}?mode=ro".format(DB_PATH.as_posix()), uri=True)
        cls.rows = classified_studies(cls.con)

    @classmethod
    def tearDownClass(cls):
        cls.con.close()

    def counts(self):
        totals = dict.fromkeys(CLASSES, 0)
        for _, _, sponsor_class in self.rows:
            totals[sponsor_class] += 1
        return totals

    def test_the_classification_covers_the_corpus_it_claims_to(self):
        totals = self.counts()
        self.assertEqual(sum(totals.values()), 11834)
        self.assertEqual(totals[INDUSTRY], 9475)
        self.assertEqual(totals[ACADEMIC], 1783)
        self.assertEqual(totals[UNCLASSIFIED], 576)

    def test_every_hand_written_name_matches_a_real_sponsor(self):
        # A hand table whose keys match nothing does nothing quietly. The
        # same test the centre corrections carry, for the same reason.
        for name in HAND_CLASSIFIED:
            with self.subTest(sponsor=name):
                self.assertEqual(
                    self.con.execute("SELECT count(*) FROM sponsors "
                                     "WHERE promotor = ?", (name,)
                                     ).fetchone()[0], 1)

    def test_no_unclassified_sponsor_is_large_enough_to_matter(self):
        # The hand list is drawn at five trials, so nothing above that may
        # be left unclassified. If a refresh adds one, this fails and the
        # list gets read again rather than quietly drifting.
        big = self.con.execute(
            """SELECT sp.promotor, count(*) n
                 FROM studies st
                 JOIN sponsors sp ON sp.sponsor_id = st.sponsor_id
                WHERE st.fecha_autorizacion_aemps >= '2013-01-01'
             GROUP BY sp.promotor HAVING n >= 5""").fetchall()
        unresolved = sorted(name for name, _ in big
                            if classify(name) == UNCLASSIFIED)
        # Nothing left: the second family pass settled MedSIR, whose
        # S.L. spelling says it is a commercial entity, which is the whole
        # of what Industry claims here.
        self.assertEqual(unresolved, [])

    def test_industry_and_academia_run_different_research(self):
        # The 3.3 finding, and the reason the sponsor split was worth
        # building: a tenfold difference in phase IV, and double in phase I.
        sponsor_class = {study: name for study, _, name in self.rows}
        totals = {name: [0, 0, 0] for name in CLASSES}
        for study, phase_one, phase_four in self.con.execute(
                """SELECT identificador, fase_uno, fase_cuatro FROM studies
                    WHERE fecha_autorizacion_aemps >= '2013-01-01'"""):
            row = totals[sponsor_class[study]]
            row[0] += 1
            row[1] += phase_one
            row[2] += phase_four
        industry, academic = totals[INDUSTRY], totals[ACADEMIC]
        self.assertAlmostEqual(100 * industry[2] / industry[0], 3.5, places=1)
        self.assertAlmostEqual(100 * industry[1] / industry[0], 25.5, places=1)
        self.assertAlmostEqual(100 * academic[2] / academic[0], 33.6, places=1)
        self.assertAlmostEqual(100 * academic[1] / academic[0], 12.3, places=1)

    def test_academic_phase_four_intensity_did_not_fall(self):
        # The hypothesis this chart was built to test, and it fails: the
        # corpus-wide phase IV decline is not academic sponsors doing less
        # phase IV. Their rate is flat; there are simply fewer of them.
        rows = phase_four_by_year(self.con, self.rows)
        academic = [100.0 * phase_four / trials
                    for _, name, trials, phase_four in rows
                    if name == ACADEMIC]
        industry = [100.0 * phase_four / trials
                    for _, name, trials, phase_four in rows
                    if name == INDUSTRY]
        self.assertGreater(academic[-1], academic[0])
        self.assertLess(industry[-1], industry[0] / 2)


if __name__ == "__main__":
    unittest.main()


class TestFamilies(unittest.TestCase):
    def test_the_two_blocks_of_roche_are_one_company(self):
        # They block apart because one name starts with 'F.', and several of
        # the Spanish entries say in the name that they represent the other.
        for name in ("F. Hoffmann-La Roche AG", "Roche Farma S.A.",
                     "F. Hoffman-La Roche Ltd.", "ROCHE FARMA"):
            with self.subTest(sponsor=name):
                self.assertEqual(family_of(name), "Roche")

    def test_the_two_mercks_stay_apart(self):
        # Merck & Co. and Merck KGaA split in 1917 and are different
        # companies. A 'Merck' rule would merge them.
        self.assertEqual(family_of("Merck Sharp & Dohme LLC"),
                         "Merck Sharp & Dohme (MSD)")
        self.assertEqual(family_of("Merck KGaA"), "Merck KGaA")
        self.assertNotEqual(family_of("Merck Sharp & Dohme Corp."),
                            family_of("Merck Healthcare KGaA"))

    def test_a_third_company_called_merckle_joins_neither(self):
        self.assertEqual(family_of("Merckle GmbH"), "Merckle GmbH")

    def test_the_lilly_pair_the_handoff_flagged_is_one_family(self):
        self.assertEqual(family_of("Lilly S.A."), family_of("Eli Lilly & Co."))

    def test_a_subsidiary_named_in_the_registry_joins_its_parent(self):
        # REEC often states the relationship, which means acquisitions are
        # picked up without anyone having to know about them.
        self.assertEqual(
            family_of("Prevail Therapeutics, a wholly-owned subsidiary of "
                      "Eli Lilly and Company"), "Eli Lilly")
        self.assertEqual(
            family_of("Millennium Pharmaceuticals, Inc., a wholly owned "
                      "subsidiary of Takeda Pharmaceutical Company"), "Takeda")

    def test_a_joint_venture_of_two_families_joins_neither(self):
        self.assertEqual(family_of("Sanofi Pasteur MSD"), "Sanofi Pasteur MSD")

    def test_two_laboratories_sharing_a_word_are_not_a_family(self):
        # The block key 'laboratorios' gathered 29 unrelated Spanish
        # laboratories, and produced no merge at all.
        self.assertNotEqual(family_of("Laboratorios Normon, S.A"),
                            family_of("Laboratorios Alter S.A."))

    def test_an_unmatched_sponsor_is_its_own_family(self):
        self.assertEqual(family_of("Hospital Clínic de Barcelona"),
                         "Hospital Clínic de Barcelona")

    def test_an_individual_never_reaches_a_ranking_under_their_name(self):
        self.assertEqual(family_of("Dra. Cristina Avendaño Solá"), INDIVIDUAL)

    def test_the_ranking_chart_keeps_the_biggest_family_on_top(self):
        # Same bottom-up axis as every other horizontal bar chart here.
        figure = families_figure(
            [("Novartis", 537, 10), ("Roche", 429, 13)], trials=11834)
        self.assertEqual(list(figure.data[0].y)[-1], "Novartis")
        self.assertEqual(figure.data[0].text, ("429", "537"))

    def test_family_membership_does_not_beat_an_academic_marker(self):
        # A marker is direct evidence about this entity; family membership is
        # an inference from its name. A foundation is a foundation.
        self.assertEqual(classify("Fundacion SERVIER"), ACADEMIC)
        self.assertEqual(classify("Janssen R&D Ireland"), INDUSTRY)


@requires_database
class TestFamiliesAgainstDatabase(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.con = sqlite3.connect(
            "file:{}?mode=ro".format(DB_PATH.as_posix()), uri=True)
        cls.families = top_families(cls.con, count=5)

    @classmethod
    def tearDownClass(cls):
        cls.con.close()

    def test_every_pattern_matches_a_real_sponsor(self):
        # A pattern matching nothing does nothing, and says nothing while it
        # does it -- the same test the centre corrections and the hand
        # classifications carry.
        names = [row[0] for row in self.con.execute(
            "SELECT promotor FROM sponsors")]
        for pattern, family in FAMILIES:
            with self.subTest(family=family):
                self.assertTrue(any(re.search(pattern, name, re.IGNORECASE)
                                    for name in names))

    def test_the_merge_changes_who_leads_the_ranking(self):
        # Unmerged, AstraZeneca AB leads with 348 -- a legal entity. Merged,
        # Novartis leads with 537, and Roche comes second from a name that
        # was not in the top five at all.
        unmerged = self.con.execute(
            """SELECT sp.promotor, count(*) n
                 FROM studies st
                 JOIN sponsors sp ON sp.sponsor_id = st.sponsor_id
                WHERE st.fecha_autorizacion_aemps >= '2013-01-01'
             GROUP BY sp.promotor ORDER BY n DESC LIMIT 1""").fetchone()
        self.assertEqual(unmerged, ("AstraZeneca AB", 348))
        self.assertEqual([(family, trials) for family, trials, _
                          in self.families[:2]],
                         [("Novartis", 537), ("Roche", 481)])

    def test_the_spelling_counts_are_what_the_merge_collapsed(self):
        spellings = {family: count for family, _, count in self.families}
        self.assertEqual(spellings["Novartis"], 10)
        self.assertEqual(spellings["Roche"], 14)


class TestReviewPage(unittest.TestCase):
    MERGED = [("Roche", 481, [("F. Hoffmann-La Roche AG", 172),
                              ("Roche Farma S.A.", 82)])]
    UNMERGED = [("Novo Nordisk A/S", 102, INDUSTRY),
                ("Merck Sharp & Dohme Copr.", 1, INDUSTRY)]

    def setUp(self):
        self.page = review_page(self.MERGED, self.UNMERGED)

    def test_both_tables_are_on_the_page(self):
        # The second one is the point: a rule cannot report the merge it
        # failed to make, so what was left alone has to be readable too.
        self.assertIn("1 families", self.page)
        self.assertIn("2 sponsors joined no family", self.page)

    def test_a_family_lists_the_spellings_it_collapsed(self):
        self.assertIn("F. Hoffmann-La Roche AG", self.page)
        self.assertIn("in 2 spellings", self.page)

    def test_ampersands_in_sponsor_names_are_escaped(self):
        # 'Merck Sharp & Dohme' would otherwise open an entity and eat the
        # rest of the cell.
        self.assertIn("Merck Sharp &amp; Dohme", self.page)
        self.assertNotIn("Dohme & Copr", self.page)

    def test_the_page_needs_no_network(self):
        # Same rule as the ERD: a review artifact that only renders online
        # is not a review artifact.
        self.assertNotIn("http://", self.page)
        self.assertNotIn("https://", self.page)


@requires_database
class TestReviewAgainstDatabase(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.con = sqlite3.connect(
            "file:{}?mode=ro".format(DB_PATH.as_posix()), uri=True)
        cls.merged, cls.unmerged = family_review(cls.con)

    @classmethod
    def tearDownClass(cls):
        cls.con.close()

    def test_the_two_tables_account_for_every_sponsor(self):
        spellings = sum(len(members) for _, _, members in self.merged)
        self.assertEqual(spellings + len(self.unmerged), 2957)

    def test_the_two_tables_account_for_every_trial(self):
        merged = sum(total for _, total, _ in self.merged)
        unmerged = sum(total for _, total, _ in self.unmerged)
        self.assertEqual(merged + unmerged, 11834)

    def test_nothing_in_the_unmerged_table_has_a_family(self):
        # If it did, the review page would be lying about what it merged.
        for name, _, _ in self.unmerged:
            self.assertEqual(family_of(name), name)

    def test_the_second_pass_families_are_all_there(self):
        # Found by reading the unmerged table, which is what it is for.
        families = {family: total for family, total, _ in self.merged}
        self.assertEqual(families["UCB"], 71)
        self.assertEqual(families["BeiGene (BeOne Medicines)"], 47)
        self.assertEqual(families["Eisai"], 29)
        self.assertEqual(families["ViiV Healthcare"], 28)
